-- ═══════════════════════════════════════════════════════════════════════════
-- BUKU — initial schema
--
-- PART 0  Extensions (pre-installed by the superuser in docker/postgres/init;
--         repeated here with IF NOT EXISTS so a managed database with
--         extension rights, e.g. DigitalOcean doadmin, gets them too).
-- PART 1  Generated by `prisma migrate diff` from schema.prisma, with ONE
--         manual edit: audit_logs / notifications / ad_events are declared
--         PARTITION BY RANGE ("created_at").
-- PART 2  Hand-written constraints, triggers and partitions.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── PART 0 ──
CREATE SCHEMA IF NOT EXISTS "extensions";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto"  SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pg_trgm"   SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "btree_gist" SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "postgis"   SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "vector"    SCHEMA "extensions";

-- ── PART 1 (prisma migrate diff) ──
-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('user', 'staff', 'business_owner', 'super_admin');

-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('active', 'suspended', 'deleted');

-- CreateEnum
CREATE TYPE "OAuthProvider" AS ENUM ('google', 'apple');

-- CreateEnum
CREATE TYPE "DevicePlatform" AS ENUM ('ios', 'android', 'web');

-- CreateEnum
CREATE TYPE "BusinessStatus" AS ENUM ('pending', 'verified', 'suspended', 'rejected');

-- CreateEnum
CREATE TYPE "SubscriptionTier" AS ENUM ('free', 'professional', 'enterprise');

-- CreateEnum
CREATE TYPE "DocumentType" AS ENUM ('business_license', 'medical_license', 'id_proof', 'address_proof');

-- CreateEnum
CREATE TYPE "DocumentStatus" AS ENUM ('pending', 'approved', 'rejected');

-- CreateEnum
CREATE TYPE "StaffRole" AS ENUM ('owner', 'manager', 'staff');

-- CreateEnum
CREATE TYPE "ExceptionType" AS ENUM ('holiday', 'modified', 'extra_hours');

-- CreateEnum
CREATE TYPE "AppointmentStatus" AS ENUM ('pending', 'confirmed', 'rescheduled', 'completed', 'cancelled', 'no_show');

-- CreateEnum
CREATE TYPE "AppointmentPaymentStatus" AS ENUM ('unpaid', 'deposit_paid', 'paid', 'refunded');

-- CreateEnum
CREATE TYPE "PaymentStatus" AS ENUM ('pending', 'authorized', 'captured', 'refunded', 'failed');

-- CreateEnum
CREATE TYPE "ActorType" AS ENUM ('user', 'business', 'system');

-- CreateEnum
CREATE TYPE "QueueSessionStatus" AS ENUM ('open', 'paused', 'closed');

-- CreateEnum
CREATE TYPE "QueueEntryStatus" AS ENUM ('waiting', 'called', 'serving', 'completed', 'left', 'no_show');

-- CreateEnum
CREATE TYPE "NotificationChannel" AS ENUM ('push', 'sms', 'email', 'in_app');

-- CreateEnum
CREATE TYPE "NotificationStatus" AS ENUM ('pending', 'sent', 'delivered', 'failed', 'read');

-- CreateEnum
CREATE TYPE "AdType" AS ENUM ('featured_listing', 'category_spotlight', 'city_banner', 'appointment_boost', 'new_user_promo');

-- CreateEnum
CREATE TYPE "AdStatus" AS ENUM ('draft', 'pending_approval', 'active', 'paused', 'expired', 'rejected');

-- CreateEnum
CREATE TYPE "AdEventType" AS ENUM ('impression', 'click', 'booking', 'profile_view');

-- CreateEnum
CREATE TYPE "AiCallOutcome" AS ENUM ('booked', 'not_booked', 'transferred', 'error');

-- CreateEnum
CREATE TYPE "SubscriptionStatus" AS ENUM ('active', 'past_due', 'cancelled', 'paused', 'trialing');

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL,
    "email_encrypted" TEXT,
    "email_hash" CHAR(64),
    "phone_encrypted" TEXT,
    "phone_hash" CHAR(64),
    "password_hash" VARCHAR(255),
    "name" VARCHAR(200) NOT NULL,
    "avatar_url" TEXT,
    "timezone" VARCHAR(60) NOT NULL DEFAULT 'UTC',
    "locale" VARCHAR(10) NOT NULL DEFAULT 'en',
    "role" "UserRole" NOT NULL DEFAULT 'user',
    "status" "UserStatus" NOT NULL DEFAULT 'active',
    "email_verified_at" TIMESTAMPTZ(6),
    "phone_verified_at" TIMESTAMPTZ(6),
    "terms_version" VARCHAR(20),
    "terms_accepted_at" TIMESTAMPTZ(6),
    "password_changed_at" TIMESTAMPTZ(6),
    "last_login_at" TIMESTAMPTZ(6),
    "deleted_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "oauth_accounts" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "provider" "OAuthProvider" NOT NULL,
    "provider_user_id" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "oauth_accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refresh_tokens" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "family_id" UUID NOT NULL,
    "token_hash" CHAR(64) NOT NULL,
    "device_info" JSONB,
    "ip_address" VARCHAR(45),
    "user_agent" VARCHAR(500),
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "last_used_at" TIMESTAMPTZ(6),
    "revoked_at" TIMESTAMPTZ(6),
    "revoked_reason" VARCHAR(50),
    "replaced_by_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "push_tokens" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "token" TEXT NOT NULL,
    "platform" "DevicePlatform" NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "last_seen_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "push_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notification_preferences" (
    "user_id" UUID NOT NULL,
    "push_booking_confirmation" BOOLEAN NOT NULL DEFAULT true,
    "push_reminders" BOOLEAN NOT NULL DEFAULT true,
    "push_queue_updates" BOOLEAN NOT NULL DEFAULT true,
    "sms_reminders" BOOLEAN NOT NULL DEFAULT true,
    "email_booking_confirmation" BOOLEAN NOT NULL DEFAULT true,
    "marketing_emails" BOOLEAN NOT NULL DEFAULT false,
    "marketing_consent_at" TIMESTAMPTZ(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "notification_preferences_pkey" PRIMARY KEY ("user_id")
);

-- CreateTable
CREATE TABLE "categories" (
    "id" UUID NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "slug" VARCHAR(100) NOT NULL,
    "icon" VARCHAR(10),
    "parent_id" UUID,
    "depth" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "categories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "businesses" (
    "id" UUID NOT NULL,
    "owner_id" UUID NOT NULL,
    "category_id" UUID NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "slug" VARCHAR(200) NOT NULL,
    "description" TEXT,
    "phone" VARCHAR(20),
    "email" VARCHAR(255),
    "website" VARCHAR(500),
    "address" TEXT,
    "city" VARCHAR(100) NOT NULL,
    "state" VARCHAR(100),
    "country" VARCHAR(100) NOT NULL,
    "postal_code" VARCHAR(20),
    "lat" DECIMAL(10,8),
    "lng" DECIMAL(11,8),
    "location" geography(Point,4326),
    "search_vector" tsvector,
    "timezone" VARCHAR(60) NOT NULL DEFAULT 'UTC',
    "currency" CHAR(3) NOT NULL DEFAULT 'USD',
    "status" "BusinessStatus" NOT NULL DEFAULT 'pending',
    "verified" BOOLEAN NOT NULL DEFAULT false,
    "verified_at" TIMESTAMPTZ(6),
    "rejection_reason" TEXT,
    "settings" JSONB NOT NULL DEFAULT '{}',
    "subscription_tier" "SubscriptionTier" NOT NULL DEFAULT 'free',
    "subscription_expires_at" TIMESTAMPTZ(6),
    "avg_rating" DECIMAL(3,2) NOT NULL DEFAULT 0,
    "review_count" INTEGER NOT NULL DEFAULT 0,
    "deleted_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "businesses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "business_photos" (
    "id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "url" TEXT NOT NULL,
    "alt_text" VARCHAR(300),
    "is_primary" BOOLEAN NOT NULL DEFAULT false,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "business_photos_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "business_documents" (
    "id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "type" "DocumentType" NOT NULL,
    "url" TEXT NOT NULL,
    "status" "DocumentStatus" NOT NULL DEFAULT 'pending',
    "reviewed_by_id" UUID,
    "reviewed_at" TIMESTAMPTZ(6),
    "review_note" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "business_documents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "business_hours" (
    "id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "day_of_week" SMALLINT NOT NULL,
    "open_time" VARCHAR(5) NOT NULL,
    "close_time" VARCHAR(5) NOT NULL,
    "is_closed" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "business_hours_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "services" (
    "id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "description" TEXT,
    "duration_minutes" INTEGER NOT NULL,
    "buffer_minutes" INTEGER NOT NULL DEFAULT 0,
    "max_concurrent" INTEGER NOT NULL DEFAULT 1,
    "price" DECIMAL(10,2) NOT NULL,
    "currency" CHAR(3) NOT NULL DEFAULT 'USD',
    "deposit_required" BOOLEAN NOT NULL DEFAULT false,
    "deposit_amount" DECIMAL(10,2),
    "group_name" VARCHAR(100),
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "services_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "staff" (
    "id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "user_id" UUID,
    "display_name" VARCHAR(100) NOT NULL,
    "bio" TEXT,
    "photo_url" TEXT,
    "specializations" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "role" "StaffRole" NOT NULL DEFAULT 'staff',
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "invite_email_encrypted" TEXT,
    "invite_token_hash" CHAR(64),
    "invite_accepted" BOOLEAN NOT NULL DEFAULT false,
    "invite_expires_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "staff_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "staff_services" (
    "staff_id" UUID NOT NULL,
    "service_id" UUID NOT NULL,

    CONSTRAINT "staff_services_pkey" PRIMARY KEY ("staff_id","service_id")
);

-- CreateTable
CREATE TABLE "resources" (
    "id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "type" VARCHAR(50) NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "resources_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "availability_rules" (
    "id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "staff_id" UUID,
    "resource_id" UUID,
    "day_of_week" SMALLINT NOT NULL,
    "start_time" VARCHAR(5) NOT NULL,
    "end_time" VARCHAR(5) NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "availability_rules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "availability_exceptions" (
    "id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "staff_id" UUID,
    "resource_id" UUID,
    "exception_date" DATE NOT NULL,
    "type" "ExceptionType" NOT NULL,
    "start_time" VARCHAR(5),
    "end_time" VARCHAR(5),
    "reason" VARCHAR(200),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "availability_exceptions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "appointments" (
    "id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "service_id" UUID NOT NULL,
    "staff_id" UUID,
    "user_id" UUID NOT NULL,
    "resource_id" UUID,
    "status" "AppointmentStatus" NOT NULL DEFAULT 'pending',
    "start_at" TIMESTAMPTZ(6) NOT NULL,
    "end_at" TIMESTAMPTZ(6) NOT NULL,
    "notes" TEXT,
    "internal_notes" TEXT,
    "price" DECIMAL(10,2) NOT NULL,
    "currency" CHAR(3) NOT NULL,
    "payment_status" "AppointmentPaymentStatus" NOT NULL DEFAULT 'unpaid',
    "version" INTEGER NOT NULL DEFAULT 1,
    "confirmation_code" VARCHAR(20) NOT NULL,
    "reminder_24h_sent_at" TIMESTAMPTZ(6),
    "reminder_2h_sent_at" TIMESTAMPTZ(6),
    "cancelled_at" TIMESTAMPTZ(6),
    "cancel_reason" TEXT,
    "cancelled_by" "ActorType",
    "rescheduled_from_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "appointments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "appointment_status_history" (
    "id" UUID NOT NULL,
    "appointment_id" UUID NOT NULL,
    "from_status" "AppointmentStatus",
    "to_status" "AppointmentStatus" NOT NULL,
    "actor_type" "ActorType" NOT NULL,
    "actor_id" UUID,
    "reason" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "appointment_status_history_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "payments" (
    "id" UUID NOT NULL,
    "appointment_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "amount" DECIMAL(10,2) NOT NULL,
    "currency" CHAR(3) NOT NULL,
    "platform_fee" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "status" "PaymentStatus" NOT NULL DEFAULT 'pending',
    "method" VARCHAR(30),
    "provider_transaction_id" VARCHAR(200),
    "refund_id" VARCHAR(200),
    "captured_at" TIMESTAMPTZ(6),
    "refunded_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "payments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "reviews" (
    "id" UUID NOT NULL,
    "appointment_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "overall_rating" SMALLINT NOT NULL,
    "wait_time_rating" SMALLINT,
    "staff_rating" SMALLINT,
    "cleanliness_rating" SMALLINT,
    "value_rating" SMALLINT,
    "comment" TEXT,
    "owner_response" TEXT,
    "owner_responded_at" TIMESTAMPTZ(6),
    "is_flagged" BOOLEAN NOT NULL DEFAULT false,
    "flag_reason" VARCHAR(200),
    "is_visible" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "reviews_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "favourites" (
    "user_id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "favourites_pkey" PRIMARY KEY ("user_id","business_id")
);

-- CreateTable
CREATE TABLE "queue_sessions" (
    "id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "session_date" DATE NOT NULL,
    "status" "QueueSessionStatus" NOT NULL DEFAULT 'open',
    "ticket_prefix" VARCHAR(5) NOT NULL DEFAULT 'A',
    "current_number" INTEGER NOT NULL DEFAULT 0,
    "last_called_number" INTEGER NOT NULL DEFAULT 0,
    "total_served" INTEGER NOT NULL DEFAULT 0,
    "avg_service_seconds" INTEGER NOT NULL DEFAULT 300,
    "max_queue_size" INTEGER NOT NULL DEFAULT 200,
    "grace_period_seconds" INTEGER NOT NULL DEFAULT 300,
    "opened_at" TIMESTAMPTZ(6),
    "closed_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "queue_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "queue_entries" (
    "id" UUID NOT NULL,
    "session_id" UUID NOT NULL,
    "user_id" UUID,
    "ticket_number" INTEGER NOT NULL,
    "ticket_prefix" VARCHAR(5) NOT NULL DEFAULT 'A',
    "status" "QueueEntryStatus" NOT NULL DEFAULT 'waiting',
    "estimated_wait_seconds" INTEGER,
    "priority_lane" BOOLEAN NOT NULL DEFAULT false,
    "notes" VARCHAR(500),
    "joined_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "called_at" TIMESTAMPTZ(6),
    "served_at" TIMESTAMPTZ(6),
    "completed_at" TIMESTAMPTZ(6),
    "left_at" TIMESTAMPTZ(6),
    "actual_service_seconds" INTEGER,

    CONSTRAINT "queue_entries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notifications" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "appointment_id" UUID,
    "queue_entry_id" UUID,
    "type" VARCHAR(50) NOT NULL,
    "channel" "NotificationChannel" NOT NULL,
    "title" VARCHAR(200) NOT NULL,
    "body" TEXT NOT NULL,
    "data" JSONB,
    "status" "NotificationStatus" NOT NULL DEFAULT 'pending',
    "external_id" VARCHAR(500),
    "failure_reason" TEXT,
    "sent_at" TIMESTAMPTZ(6),
    "delivered_at" TIMESTAMPTZ(6),
    "read_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id","created_at")
) PARTITION BY RANGE ("created_at");

-- CreateTable
CREATE TABLE "business_ads" (
    "id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "type" "AdType" NOT NULL,
    "category_id" UUID,
    "city" VARCHAR(100),
    "country" VARCHAR(100),
    "status" "AdStatus" NOT NULL DEFAULT 'draft',
    "start_date" TIMESTAMPTZ(6) NOT NULL,
    "end_date" TIMESTAMPTZ(6) NOT NULL,
    "weekly_budget" DECIMAL(10,2),
    "total_budget" DECIMAL(10,2) NOT NULL,
    "amount_spent" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "impressions" INTEGER NOT NULL DEFAULT 0,
    "clicks" INTEGER NOT NULL DEFAULT 0,
    "bookings" INTEGER NOT NULL DEFAULT 0,
    "revenue_attributed" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "rejection_reason" TEXT,
    "payment_method" VARCHAR(30),
    "payment_ref" VARCHAR(200),
    "paid_at" TIMESTAMPTZ(6),
    "approved_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "business_ads_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ad_events" (
    "id" UUID NOT NULL,
    "ad_id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "user_id" UUID,
    "type" "AdEventType" NOT NULL,
    "session_id" VARCHAR(100),
    "ip_hash" CHAR(64),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ad_events_pkey" PRIMARY KEY ("id","created_at")
) PARTITION BY RANGE ("created_at");

-- CreateTable
CREATE TABLE "ai_receptionist_configs" (
    "id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "is_enabled" BOOLEAN NOT NULL DEFAULT false,
    "phone_number" VARCHAR(20),
    "voice_id" VARCHAR(100),
    "greeting_message" TEXT,
    "business_context" TEXT,
    "active_overrides" JSONB NOT NULL DEFAULT '[]',
    "total_calls_handled" INTEGER NOT NULL DEFAULT 0,
    "total_bookings_made" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "ai_receptionist_configs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_call_logs" (
    "id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "caller_phone_encrypted" TEXT,
    "duration_seconds" INTEGER,
    "transcript_url" TEXT,
    "appointment_id" UUID,
    "outcome" "AiCallOutcome" NOT NULL,
    "failure_reason" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_call_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "webhooks" (
    "id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "url" TEXT NOT NULL,
    "secret_encrypted" TEXT NOT NULL,
    "events" TEXT[],
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "last_triggered_at" TIMESTAMPTZ(6),
    "failure_count" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "webhooks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "webhook_deliveries" (
    "id" UUID NOT NULL,
    "webhook_id" UUID NOT NULL,
    "event_id" UUID NOT NULL,
    "event_type" VARCHAR(100) NOT NULL,
    "payload" JSONB NOT NULL,
    "response_status" INTEGER,
    "response_body" TEXT,
    "attempt_count" INTEGER NOT NULL DEFAULT 1,
    "delivered_at" TIMESTAMPTZ(6),
    "next_retry_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "webhook_deliveries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "subscriptions" (
    "id" UUID NOT NULL,
    "business_id" UUID NOT NULL,
    "paddle_subscription_id" VARCHAR(200) NOT NULL,
    "paddle_customer_id" VARCHAR(200) NOT NULL,
    "plan" "SubscriptionTier" NOT NULL,
    "status" "SubscriptionStatus" NOT NULL,
    "current_period_start" TIMESTAMPTZ(6),
    "current_period_end" TIMESTAMPTZ(6),
    "cancel_at_period_end" BOOLEAN NOT NULL DEFAULT false,
    "cancelled_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "subscriptions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_logs" (
    "id" UUID NOT NULL,
    "user_id" UUID,
    "action" VARCHAR(100) NOT NULL,
    "resource_type" VARCHAR(50) NOT NULL,
    "resource_id" UUID,
    "old_values" JSONB,
    "new_values" JSONB,
    "ip_address" VARCHAR(45),
    "user_agent" VARCHAR(500),
    "request_id" VARCHAR(128),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id","created_at")
) PARTITION BY RANGE ("created_at");

-- CreateTable
CREATE TABLE "outbox_events" (
    "id" UUID NOT NULL,
    "aggregate_type" VARCHAR(50) NOT NULL,
    "aggregate_id" UUID NOT NULL,
    "topic" VARCHAR(100) NOT NULL,
    "partition_key" VARCHAR(100) NOT NULL,
    "payload" JSONB NOT NULL,
    "headers" JSONB,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "last_error" TEXT,
    "published_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "outbox_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "processed_events" (
    "consumer" VARCHAR(100) NOT NULL,
    "event_id" VARCHAR(200) NOT NULL,
    "processed_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "processed_events_pkey" PRIMARY KEY ("consumer","event_id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_hash_key" ON "users"("email_hash");

-- CreateIndex
CREATE UNIQUE INDEX "users_phone_hash_key" ON "users"("phone_hash");

-- CreateIndex
CREATE INDEX "users_status_idx" ON "users"("status");

-- CreateIndex
CREATE INDEX "users_created_at_idx" ON "users"("created_at");

-- CreateIndex
CREATE INDEX "users_deleted_at_idx" ON "users"("deleted_at");

-- CreateIndex
CREATE INDEX "oauth_accounts_user_id_idx" ON "oauth_accounts"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "oauth_accounts_provider_provider_user_id_key" ON "oauth_accounts"("provider", "provider_user_id");

-- CreateIndex
CREATE UNIQUE INDEX "refresh_tokens_token_hash_key" ON "refresh_tokens"("token_hash");

-- CreateIndex
CREATE INDEX "refresh_tokens_user_id_idx" ON "refresh_tokens"("user_id");

-- CreateIndex
CREATE INDEX "refresh_tokens_family_id_idx" ON "refresh_tokens"("family_id");

-- CreateIndex
CREATE INDEX "refresh_tokens_expires_at_idx" ON "refresh_tokens"("expires_at");

-- CreateIndex
CREATE UNIQUE INDEX "push_tokens_token_key" ON "push_tokens"("token");

-- CreateIndex
CREATE INDEX "push_tokens_user_id_is_active_idx" ON "push_tokens"("user_id", "is_active");

-- CreateIndex
CREATE UNIQUE INDEX "categories_slug_key" ON "categories"("slug");

-- CreateIndex
CREATE INDEX "categories_parent_id_idx" ON "categories"("parent_id");

-- CreateIndex
CREATE INDEX "categories_is_active_sort_order_idx" ON "categories"("is_active", "sort_order");

-- CreateIndex
CREATE UNIQUE INDEX "businesses_slug_key" ON "businesses"("slug");

-- CreateIndex
CREATE INDEX "businesses_owner_id_idx" ON "businesses"("owner_id");

-- CreateIndex
CREATE INDEX "businesses_category_id_idx" ON "businesses"("category_id");

-- CreateIndex
CREATE INDEX "businesses_status_verified_idx" ON "businesses"("status", "verified");

-- CreateIndex
CREATE INDEX "businesses_city_country_idx" ON "businesses"("city", "country");

-- CreateIndex
CREATE INDEX "businesses_avg_rating_idx" ON "businesses"("avg_rating");

-- CreateIndex
CREATE INDEX "businesses_created_at_idx" ON "businesses"("created_at");

-- CreateIndex
CREATE INDEX "businesses_location_idx" ON "businesses" USING GIST ("location");

-- CreateIndex
CREATE INDEX "businesses_search_vector_idx" ON "businesses" USING GIN ("search_vector");

-- CreateIndex
CREATE INDEX "businesses_name_trgm_idx" ON "businesses" USING GIN ("name" gin_trgm_ops);

-- CreateIndex
CREATE INDEX "business_photos_business_id_sort_order_idx" ON "business_photos"("business_id", "sort_order");

-- CreateIndex
CREATE INDEX "business_documents_business_id_idx" ON "business_documents"("business_id");

-- CreateIndex
CREATE INDEX "business_documents_status_created_at_idx" ON "business_documents"("status", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "business_hours_business_id_day_of_week_open_time_key" ON "business_hours"("business_id", "day_of_week", "open_time");

-- CreateIndex
CREATE INDEX "services_business_id_is_active_sort_order_idx" ON "services"("business_id", "is_active", "sort_order");

-- CreateIndex
CREATE UNIQUE INDEX "staff_invite_token_hash_key" ON "staff"("invite_token_hash");

-- CreateIndex
CREATE INDEX "staff_business_id_is_active_idx" ON "staff"("business_id", "is_active");

-- CreateIndex
CREATE INDEX "staff_user_id_idx" ON "staff"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "staff_business_id_user_id_key" ON "staff"("business_id", "user_id");

-- CreateIndex
CREATE INDEX "staff_services_service_id_idx" ON "staff_services"("service_id");

-- CreateIndex
CREATE INDEX "resources_business_id_is_active_idx" ON "resources"("business_id", "is_active");

-- CreateIndex
CREATE INDEX "availability_rules_business_id_day_of_week_idx" ON "availability_rules"("business_id", "day_of_week");

-- CreateIndex
CREATE INDEX "availability_rules_staff_id_day_of_week_idx" ON "availability_rules"("staff_id", "day_of_week");

-- CreateIndex
CREATE INDEX "availability_exceptions_business_id_exception_date_idx" ON "availability_exceptions"("business_id", "exception_date");

-- CreateIndex
CREATE INDEX "availability_exceptions_staff_id_exception_date_idx" ON "availability_exceptions"("staff_id", "exception_date");

-- CreateIndex
CREATE UNIQUE INDEX "appointments_confirmation_code_key" ON "appointments"("confirmation_code");

-- CreateIndex
CREATE UNIQUE INDEX "appointments_rescheduled_from_id_key" ON "appointments"("rescheduled_from_id");

-- CreateIndex
CREATE INDEX "appointments_business_id_start_at_idx" ON "appointments"("business_id", "start_at");

-- CreateIndex
CREATE INDEX "appointments_user_id_start_at_idx" ON "appointments"("user_id", "start_at");

-- CreateIndex
CREATE INDEX "appointments_staff_id_start_at_idx" ON "appointments"("staff_id", "start_at");

-- CreateIndex
CREATE INDEX "appointments_status_start_at_idx" ON "appointments"("status", "start_at");

-- CreateIndex
CREATE INDEX "appointments_created_at_idx" ON "appointments"("created_at");

-- CreateIndex
CREATE INDEX "appointment_status_history_appointment_id_created_at_idx" ON "appointment_status_history"("appointment_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "payments_appointment_id_key" ON "payments"("appointment_id");

-- CreateIndex
CREATE UNIQUE INDEX "payments_provider_transaction_id_key" ON "payments"("provider_transaction_id");

-- CreateIndex
CREATE INDEX "payments_user_id_created_at_idx" ON "payments"("user_id", "created_at");

-- CreateIndex
CREATE INDEX "payments_business_id_created_at_idx" ON "payments"("business_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "reviews_appointment_id_key" ON "reviews"("appointment_id");

-- CreateIndex
CREATE INDEX "reviews_business_id_is_visible_created_at_idx" ON "reviews"("business_id", "is_visible", "created_at");

-- CreateIndex
CREATE INDEX "reviews_business_id_overall_rating_idx" ON "reviews"("business_id", "overall_rating");

-- CreateIndex
CREATE INDEX "reviews_user_id_idx" ON "reviews"("user_id");

-- CreateIndex
CREATE INDEX "favourites_business_id_idx" ON "favourites"("business_id");

-- CreateIndex
CREATE INDEX "queue_sessions_status_session_date_idx" ON "queue_sessions"("status", "session_date");

-- CreateIndex
CREATE UNIQUE INDEX "queue_sessions_business_id_session_date_key" ON "queue_sessions"("business_id", "session_date");

-- CreateIndex
CREATE INDEX "queue_entries_session_id_status_idx" ON "queue_entries"("session_id", "status");

-- CreateIndex
CREATE INDEX "queue_entries_user_id_joined_at_idx" ON "queue_entries"("user_id", "joined_at");

-- CreateIndex
CREATE UNIQUE INDEX "queue_entries_session_id_ticket_number_key" ON "queue_entries"("session_id", "ticket_number");

-- CreateIndex
CREATE INDEX "notifications_user_id_created_at_idx" ON "notifications"("user_id", "created_at");

-- CreateIndex
CREATE INDEX "notifications_user_id_read_at_idx" ON "notifications"("user_id", "read_at");

-- CreateIndex
CREATE INDEX "notifications_status_created_at_idx" ON "notifications"("status", "created_at");

-- CreateIndex
CREATE INDEX "business_ads_business_id_status_idx" ON "business_ads"("business_id", "status");

-- CreateIndex
CREATE INDEX "business_ads_status_start_date_end_date_idx" ON "business_ads"("status", "start_date", "end_date");

-- CreateIndex
CREATE INDEX "business_ads_type_city_country_status_idx" ON "business_ads"("type", "city", "country", "status");

-- CreateIndex
CREATE INDEX "ad_events_ad_id_type_created_at_idx" ON "ad_events"("ad_id", "type", "created_at");

-- CreateIndex
CREATE INDEX "ad_events_business_id_type_created_at_idx" ON "ad_events"("business_id", "type", "created_at");

-- CreateIndex
CREATE INDEX "ad_events_user_id_type_created_at_idx" ON "ad_events"("user_id", "type", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "ai_receptionist_configs_business_id_key" ON "ai_receptionist_configs"("business_id");

-- CreateIndex
CREATE INDEX "ai_call_logs_business_id_created_at_idx" ON "ai_call_logs"("business_id", "created_at");

-- CreateIndex
CREATE INDEX "webhooks_business_id_is_active_idx" ON "webhooks"("business_id", "is_active");

-- CreateIndex
CREATE INDEX "webhook_deliveries_webhook_id_created_at_idx" ON "webhook_deliveries"("webhook_id", "created_at");

-- CreateIndex
CREATE INDEX "webhook_deliveries_next_retry_at_idx" ON "webhook_deliveries"("next_retry_at");

-- CreateIndex
CREATE UNIQUE INDEX "webhook_deliveries_webhook_id_event_id_key" ON "webhook_deliveries"("webhook_id", "event_id");

-- CreateIndex
CREATE UNIQUE INDEX "subscriptions_paddle_subscription_id_key" ON "subscriptions"("paddle_subscription_id");

-- CreateIndex
CREATE INDEX "subscriptions_business_id_status_idx" ON "subscriptions"("business_id", "status");

-- CreateIndex
CREATE INDEX "audit_logs_user_id_created_at_idx" ON "audit_logs"("user_id", "created_at");

-- CreateIndex
CREATE INDEX "audit_logs_resource_type_resource_id_created_at_idx" ON "audit_logs"("resource_type", "resource_id", "created_at");

-- CreateIndex
CREATE INDEX "audit_logs_action_created_at_idx" ON "audit_logs"("action", "created_at");

-- CreateIndex
CREATE INDEX "outbox_events_published_at_created_at_idx" ON "outbox_events"("published_at", "created_at");

-- CreateIndex
CREATE INDEX "outbox_events_aggregate_type_aggregate_id_idx" ON "outbox_events"("aggregate_type", "aggregate_id");

-- CreateIndex
CREATE INDEX "processed_events_processed_at_idx" ON "processed_events"("processed_at");

-- AddForeignKey
ALTER TABLE "oauth_accounts" ADD CONSTRAINT "oauth_accounts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "push_tokens" ADD CONSTRAINT "push_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification_preferences" ADD CONSTRAINT "notification_preferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "categories" ADD CONSTRAINT "categories_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "businesses" ADD CONSTRAINT "businesses_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "businesses" ADD CONSTRAINT "businesses_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "business_photos" ADD CONSTRAINT "business_photos_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "business_documents" ADD CONSTRAINT "business_documents_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "business_documents" ADD CONSTRAINT "business_documents_reviewed_by_id_fkey" FOREIGN KEY ("reviewed_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "business_hours" ADD CONSTRAINT "business_hours_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "services" ADD CONSTRAINT "services_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "staff" ADD CONSTRAINT "staff_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "staff" ADD CONSTRAINT "staff_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "staff_services" ADD CONSTRAINT "staff_services_staff_id_fkey" FOREIGN KEY ("staff_id") REFERENCES "staff"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "staff_services" ADD CONSTRAINT "staff_services_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "resources" ADD CONSTRAINT "resources_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "availability_rules" ADD CONSTRAINT "availability_rules_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "availability_rules" ADD CONSTRAINT "availability_rules_staff_id_fkey" FOREIGN KEY ("staff_id") REFERENCES "staff"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "availability_rules" ADD CONSTRAINT "availability_rules_resource_id_fkey" FOREIGN KEY ("resource_id") REFERENCES "resources"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "availability_exceptions" ADD CONSTRAINT "availability_exceptions_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "availability_exceptions" ADD CONSTRAINT "availability_exceptions_staff_id_fkey" FOREIGN KEY ("staff_id") REFERENCES "staff"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "availability_exceptions" ADD CONSTRAINT "availability_exceptions_resource_id_fkey" FOREIGN KEY ("resource_id") REFERENCES "resources"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_staff_id_fkey" FOREIGN KEY ("staff_id") REFERENCES "staff"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_resource_id_fkey" FOREIGN KEY ("resource_id") REFERENCES "resources"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_rescheduled_from_id_fkey" FOREIGN KEY ("rescheduled_from_id") REFERENCES "appointments"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointment_status_history" ADD CONSTRAINT "appointment_status_history_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payments" ADD CONSTRAINT "payments_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payments" ADD CONSTRAINT "payments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payments" ADD CONSTRAINT "payments_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "favourites" ADD CONSTRAINT "favourites_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "favourites" ADD CONSTRAINT "favourites_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "queue_sessions" ADD CONSTRAINT "queue_sessions_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "queue_entries" ADD CONSTRAINT "queue_entries_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "queue_sessions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "queue_entries" ADD CONSTRAINT "queue_entries_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "business_ads" ADD CONSTRAINT "business_ads_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "business_ads" ADD CONSTRAINT "business_ads_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ad_events" ADD CONSTRAINT "ad_events_ad_id_fkey" FOREIGN KEY ("ad_id") REFERENCES "business_ads"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ad_events" ADD CONSTRAINT "ad_events_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_receptionist_configs" ADD CONSTRAINT "ai_receptionist_configs_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_call_logs" ADD CONSTRAINT "ai_call_logs_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "webhooks" ADD CONSTRAINT "webhooks_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "webhook_deliveries" ADD CONSTRAINT "webhook_deliveries_webhook_id_fkey" FOREIGN KEY ("webhook_id") REFERENCES "webhooks"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ═══════════════════════════════════════════════════════════════════════════
-- PART 2 — HAND-WRITTEN: what Prisma's schema language cannot express.
-- These are integrity guarantees enforced by the database itself, so they hold
-- even if application code has a bug. Keep this list in sync with the
-- "DB extras" comments in schema.prisma.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 2.1 Derived columns on businesses ─────────────────────────────────────
-- A BEFORE trigger keeps the PostGIS point (from lat/lng) and the weighted
-- full-text vector (name A / description B / city C) in sync, so the app can
-- never write them inconsistently. (A trigger rather than GENERATED columns:
-- Prisma misreads generation expressions as column defaults and would try to
-- "fix" them in every future migration.)
CREATE FUNCTION "businesses_derive_columns"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW."lat" IS NOT NULL AND NEW."lng" IS NOT NULL THEN
    NEW."location" := extensions.ST_SetSRID(extensions.ST_MakePoint(NEW."lng"::float8, NEW."lat"::float8), 4326)::extensions.geography;
  ELSE
    NEW."location" := NULL;
  END IF;
  NEW."search_vector" :=
    setweight(to_tsvector('english'::regconfig, coalesce(NEW."name", '')), 'A') ||
    setweight(to_tsvector('english'::regconfig, coalesce(NEW."description", '')), 'B') ||
    setweight(to_tsvector('english'::regconfig, coalesce(NEW."city", '')), 'C');
  RETURN NEW;
END $$;

CREATE TRIGGER "trg_businesses_derive_columns"
  BEFORE INSERT OR UPDATE OF "lat", "lng", "name", "description", "city", "location", "search_vector" ON "businesses"
  FOR EACH ROW EXECUTE FUNCTION "businesses_derive_columns"();

-- ── 2.2 CHECK constraints ──────────────────────────────────────────────────
ALTER TABLE "users"
  ADD CONSTRAINT "chk_users_has_identifier" CHECK ("email_hash" IS NOT NULL OR "phone_hash" IS NOT NULL OR "deleted_at" IS NOT NULL),
  ADD CONSTRAINT "chk_users_email_hash_hex" CHECK ("email_hash" ~ '^[0-9a-f]{64}$'),
  ADD CONSTRAINT "chk_users_phone_hash_hex" CHECK ("phone_hash" ~ '^[0-9a-f]{64}$');

ALTER TABLE "refresh_tokens"
  ADD CONSTRAINT "chk_refresh_tokens_hash_hex" CHECK ("token_hash" ~ '^[0-9a-f]{64}$'),
  ADD CONSTRAINT "chk_refresh_tokens_expiry" CHECK ("expires_at" > "created_at");

ALTER TABLE "categories"
  ADD CONSTRAINT "chk_categories_depth" CHECK ("depth" >= 0 AND "depth" <= 5),
  ADD CONSTRAINT "chk_categories_slug" CHECK ("slug" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  ADD CONSTRAINT "chk_categories_not_own_parent" CHECK ("parent_id" IS DISTINCT FROM "id");

ALTER TABLE "businesses"
  ADD CONSTRAINT "chk_businesses_slug" CHECK ("slug" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  ADD CONSTRAINT "chk_businesses_lat" CHECK ("lat" BETWEEN -90 AND 90),
  ADD CONSTRAINT "chk_businesses_lng" CHECK ("lng" BETWEEN -180 AND 180),
  ADD CONSTRAINT "chk_businesses_latlng_pair" CHECK (("lat" IS NULL) = ("lng" IS NULL)),
  ADD CONSTRAINT "chk_businesses_rating" CHECK ("avg_rating" BETWEEN 0 AND 5),
  ADD CONSTRAINT "chk_businesses_review_count" CHECK ("review_count" >= 0),
  ADD CONSTRAINT "chk_businesses_currency" CHECK ("currency" ~ '^[A-Z]{3}$'),
  ADD CONSTRAINT "chk_businesses_settings_object" CHECK (jsonb_typeof("settings") = 'object');

ALTER TABLE "business_hours"
  ADD CONSTRAINT "chk_business_hours_day" CHECK ("day_of_week" BETWEEN 0 AND 6),
  ADD CONSTRAINT "chk_business_hours_format" CHECK ("open_time" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' AND "close_time" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  ADD CONSTRAINT "chk_business_hours_order" CHECK ("is_closed" OR "open_time" < "close_time");

ALTER TABLE "services"
  ADD CONSTRAINT "chk_services_duration" CHECK ("duration_minutes" BETWEEN 5 AND 1440),
  ADD CONSTRAINT "chk_services_buffer" CHECK ("buffer_minutes" BETWEEN 0 AND 240),
  ADD CONSTRAINT "chk_services_max_concurrent" CHECK ("max_concurrent" BETWEEN 1 AND 100),
  ADD CONSTRAINT "chk_services_price" CHECK ("price" >= 0),
  ADD CONSTRAINT "chk_services_deposit" CHECK ("deposit_amount" IS NULL OR ("deposit_amount" >= 0 AND "deposit_amount" <= "price")),
  ADD CONSTRAINT "chk_services_currency" CHECK ("currency" ~ '^[A-Z]{3}$');

ALTER TABLE "availability_rules"
  ADD CONSTRAINT "chk_availability_rules_day" CHECK ("day_of_week" BETWEEN 0 AND 6),
  ADD CONSTRAINT "chk_availability_rules_format" CHECK ("start_time" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' AND "end_time" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  ADD CONSTRAINT "chk_availability_rules_order" CHECK ("start_time" < "end_time"),
  ADD CONSTRAINT "chk_availability_rules_target" CHECK ("staff_id" IS NULL OR "resource_id" IS NULL);

ALTER TABLE "availability_exceptions"
  ADD CONSTRAINT "chk_availability_exceptions_pair" CHECK (("start_time" IS NULL) = ("end_time" IS NULL)),
  ADD CONSTRAINT "chk_availability_exceptions_format" CHECK ("start_time" IS NULL OR ("start_time" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' AND "end_time" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
  ADD CONSTRAINT "chk_availability_exceptions_order" CHECK ("start_time" IS NULL OR "start_time" < "end_time"),
  ADD CONSTRAINT "chk_availability_exceptions_hours" CHECK ("type" = 'holiday' OR "start_time" IS NOT NULL);

ALTER TABLE "appointments"
  ADD CONSTRAINT "chk_appointments_time_order" CHECK ("end_at" > "start_at"),
  ADD CONSTRAINT "chk_appointments_max_length" CHECK ("end_at" - "start_at" <= interval '24 hours'),
  ADD CONSTRAINT "chk_appointments_price" CHECK ("price" >= 0),
  ADD CONSTRAINT "chk_appointments_currency" CHECK ("currency" ~ '^[A-Z]{3}$'),
  ADD CONSTRAINT "chk_appointments_version" CHECK ("version" >= 1),
  ADD CONSTRAINT "chk_appointments_code" CHECK ("confirmation_code" ~ '^BK-[ABCDEFGHJKMNPQRSTUVWXYZ2-9]{6}$'),
  ADD CONSTRAINT "chk_appointments_cancel_fields" CHECK ("status" <> 'cancelled' OR ("cancelled_at" IS NOT NULL AND "cancelled_by" IS NOT NULL)),
  ADD CONSTRAINT "chk_appointments_not_self_reschedule" CHECK ("rescheduled_from_id" IS DISTINCT FROM "id");

ALTER TABLE "payments"
  ADD CONSTRAINT "chk_payments_amount" CHECK ("amount" >= 0),
  ADD CONSTRAINT "chk_payments_fee" CHECK ("platform_fee" >= 0 AND "platform_fee" <= "amount"),
  ADD CONSTRAINT "chk_payments_currency" CHECK ("currency" ~ '^[A-Z]{3}$');

ALTER TABLE "reviews"
  ADD CONSTRAINT "chk_reviews_overall" CHECK ("overall_rating" BETWEEN 1 AND 5),
  ADD CONSTRAINT "chk_reviews_wait" CHECK ("wait_time_rating" BETWEEN 1 AND 5),
  ADD CONSTRAINT "chk_reviews_staff" CHECK ("staff_rating" BETWEEN 1 AND 5),
  ADD CONSTRAINT "chk_reviews_cleanliness" CHECK ("cleanliness_rating" BETWEEN 1 AND 5),
  ADD CONSTRAINT "chk_reviews_value" CHECK ("value_rating" BETWEEN 1 AND 5);

ALTER TABLE "queue_sessions"
  ADD CONSTRAINT "chk_queue_sessions_counters" CHECK ("current_number" >= 0 AND "last_called_number" >= 0 AND "last_called_number" <= "current_number" AND "total_served" >= 0),
  ADD CONSTRAINT "chk_queue_sessions_avg" CHECK ("avg_service_seconds" > 0),
  ADD CONSTRAINT "chk_queue_sessions_size" CHECK ("max_queue_size" BETWEEN 1 AND 10000),
  ADD CONSTRAINT "chk_queue_sessions_grace" CHECK ("grace_period_seconds" BETWEEN 0 AND 3600);

ALTER TABLE "queue_entries"
  ADD CONSTRAINT "chk_queue_entries_ticket" CHECK ("ticket_number" > 0),
  ADD CONSTRAINT "chk_queue_entries_service_seconds" CHECK ("actual_service_seconds" IS NULL OR "actual_service_seconds" >= 0);

ALTER TABLE "business_ads"
  ADD CONSTRAINT "chk_business_ads_dates" CHECK ("end_date" > "start_date"),
  ADD CONSTRAINT "chk_business_ads_money" CHECK ("total_budget" >= 0 AND ("weekly_budget" IS NULL OR "weekly_budget" >= 0) AND "amount_spent" >= 0 AND "revenue_attributed" >= 0),
  ADD CONSTRAINT "chk_business_ads_counters" CHECK ("impressions" >= 0 AND "clicks" >= 0 AND "bookings" >= 0);

ALTER TABLE "ai_call_logs"
  ADD CONSTRAINT "chk_ai_call_logs_duration" CHECK ("duration_seconds" IS NULL OR "duration_seconds" >= 0);

ALTER TABLE "webhooks"
  ADD CONSTRAINT "chk_webhooks_url" CHECK ("url" ~ '^https?://'),
  ADD CONSTRAINT "chk_webhooks_failures" CHECK ("failure_count" >= 0),
  ADD CONSTRAINT "chk_webhooks_events" CHECK (cardinality("events") > 0);

ALTER TABLE "webhook_deliveries"
  ADD CONSTRAINT "chk_webhook_deliveries_attempts" CHECK ("attempt_count" >= 1);

ALTER TABLE "outbox_events"
  ADD CONSTRAINT "chk_outbox_events_attempts" CHECK ("attempts" >= 0);

-- ── 2.3 Exclusion constraints: no double booking, ever ─────────────────────
-- The booking service takes a Valkey lock to avoid the race; these make it
-- IMPOSSIBLE for two active appointments to overlap for the same staff member
-- or resource, even under a bug or a lock failure. '[)' = back-to-back is fine.
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_no_staff_overlap"
  EXCLUDE USING gist ("staff_id" WITH =, tstzrange("start_at", "end_at", '[)') WITH &&)
  WHERE ("staff_id" IS NOT NULL AND "status" IN ('pending', 'confirmed'));

ALTER TABLE "appointments" ADD CONSTRAINT "appointments_no_resource_overlap"
  EXCLUDE USING gist ("resource_id" WITH =, tstzrange("start_at", "end_at", '[)') WITH &&)
  WHERE ("resource_id" IS NOT NULL AND "status" IN ('pending', 'confirmed'));

-- ── 2.4 Partial unique indexes ─────────────────────────────────────────────
-- One live ticket per user per queue.
CREATE UNIQUE INDEX "queue_entries_one_active_per_user"
  ON "queue_entries" ("session_id", "user_id")
  WHERE "user_id" IS NOT NULL AND "status" IN ('waiting', 'called', 'serving');
-- One primary photo per business.
CREATE UNIQUE INDEX "business_photos_one_primary" ON "business_photos" ("business_id") WHERE "is_primary";
-- One live subscription per business.
CREATE UNIQUE INDEX "subscriptions_one_live_per_business"
  ON "subscriptions" ("business_id") WHERE "status" IN ('active', 'trialing', 'past_due', 'paused');

-- ── 2.5 AI-receptionist knowledge base (pgvector) ─────────────────────────
-- Lives in its own `ai` schema, outside Prisma's control: Prisma cannot
-- represent vector columns or HNSW indexes and would try to drop them. The
-- table is read/written through typed raw-SQL helpers in @buku/database.
CREATE SCHEMA IF NOT EXISTS "ai";

CREATE TABLE "ai"."business_knowledge_chunks" (
  "id"          UUID PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
  "business_id" UUID NOT NULL REFERENCES "public"."businesses" ("id") ON DELETE CASCADE,
  -- faq | service | policy | hours_note
  "source"      VARCHAR(50) NOT NULL CHECK ("source" IN ('faq', 'service', 'policy', 'hours_note')),
  "content"     TEXT NOT NULL CHECK (length("content") BETWEEN 1 AND 8000),
  -- text-embedding-3-small (1536 dimensions)
  "embedding"   extensions.vector(1536) NOT NULL,
  "created_at"  TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "updated_at"  TIMESTAMPTZ(6) NOT NULL DEFAULT now()
);
CREATE INDEX "business_knowledge_chunks_business_idx" ON "ai"."business_knowledge_chunks" ("business_id");
-- Approximate nearest-neighbour search by cosine distance (`<=>`).
CREATE INDEX "business_knowledge_chunks_embedding_hnsw"
  ON "ai"."business_knowledge_chunks" USING hnsw ("embedding" extensions.vector_cosine_ops);

-- ── 2.6 Triggers ───────────────────────────────────────────────────────────
-- updated_at maintained by the DB too, so raw-SQL updates can't forget it.
CREATE FUNCTION "set_updated_at"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW."updated_at" := now();
  RETURN NEW;
END $$;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'users', 'notification_preferences', 'businesses', 'services', 'appointments',
    'business_ads', 'ai_receptionist_configs', 'webhooks', 'subscriptions'
  ] LOOP
    EXECUTE format('CREATE TRIGGER "trg_%s_updated_at" BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public."set_updated_at"()', t, t);
  END LOOP;
END $$;
CREATE TRIGGER "trg_business_knowledge_chunks_updated_at" BEFORE UPDATE ON "ai"."business_knowledge_chunks"
  FOR EACH ROW EXECUTE FUNCTION public."set_updated_at"();

-- businesses.avg_rating / review_count always reflect visible reviews.
CREATE FUNCTION "recalc_business_rating"(biz uuid) RETURNS void LANGUAGE sql AS $$
  UPDATE "businesses" b SET
    "avg_rating"   = COALESCE((SELECT ROUND(AVG(r."overall_rating")::numeric, 2) FROM "reviews" r
                               WHERE r."business_id" = biz AND r."is_visible"), 0),
    "review_count" = (SELECT COUNT(*) FROM "reviews" r WHERE r."business_id" = biz AND r."is_visible")
  WHERE b."id" = biz;
$$;

CREATE FUNCTION "trg_reviews_recalc_rating"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP IN ('UPDATE', 'DELETE') THEN PERFORM "recalc_business_rating"(OLD."business_id"); END IF;
  IF TG_OP IN ('INSERT', 'UPDATE') AND (TG_OP = 'INSERT' OR NEW."business_id" IS DISTINCT FROM OLD."business_id"
       OR NEW."overall_rating" IS DISTINCT FROM OLD."overall_rating" OR NEW."is_visible" IS DISTINCT FROM OLD."is_visible") THEN
    PERFORM "recalc_business_rating"(NEW."business_id");
  END IF;
  RETURN NULL;
END $$;

CREATE TRIGGER "trg_reviews_rating"
  AFTER INSERT OR UPDATE OR DELETE ON "reviews"
  FOR EACH ROW EXECUTE FUNCTION "trg_reviews_recalc_rating"();

-- ── 2.7 Monthly partition management ───────────────────────────────────────
-- audit_logs, notifications and ad_events grow by one row per ACTION, not per
-- user, so they are range-partitioned by month (created in PART 1 below via
-- PARTITION BY). Old months are archived with DETACH PARTITION instead of a
-- slow, bloating DELETE. Child partitions live in the `partitions` schema so
-- Prisma (which manages `public`) never sees them.
CREATE SCHEMA IF NOT EXISTS "partitions";

CREATE FUNCTION "ensure_monthly_partitions"(months_ahead int DEFAULT 3, months_back int DEFAULT 1)
RETURNS int
LANGUAGE plpgsql
-- Runs with the migrator's rights so the (data-only) app role can call it
-- from a scheduled job without being able to create tables itself.
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  parent text;
  m date;
  first_month date := date_trunc('month', now() AT TIME ZONE 'UTC')::date - make_interval(months => months_back);
  last_month  date := date_trunc('month', now() AT TIME ZONE 'UTC')::date + make_interval(months => months_ahead);
  part text;
  created int := 0;
BEGIN
  IF months_ahead NOT BETWEEN 0 AND 36 OR months_back NOT BETWEEN 0 AND 36 THEN
    RAISE EXCEPTION 'months_ahead/months_back must be between 0 and 36';
  END IF;
  FOREACH parent IN ARRAY ARRAY['audit_logs', 'notifications', 'ad_events'] LOOP
    m := first_month;
    WHILE m <= last_month LOOP
      part := format('%s_%s', parent, to_char(m, 'YYYY_MM'));
      IF to_regclass(format('partitions.%I', part)) IS NULL THEN
        EXECUTE format(
          'CREATE TABLE partitions.%I PARTITION OF public.%I FOR VALUES FROM (%L) TO (%L)',
          part, parent,
          (m::timestamp AT TIME ZONE 'UTC'),
          ((m + interval '1 month')::timestamp AT TIME ZONE 'UTC'));
        created := created + 1;
      END IF;
      m := (m + interval '1 month')::date;
    END LOOP;
  END LOOP;
  RETURN created;
END $$;

REVOKE ALL ON FUNCTION "ensure_monthly_partitions"(int, int) FROM PUBLIC;

-- Safety net: rows outside every monthly range land here instead of failing.
-- (Monitor it: it should stay empty. A scheduled job creates months ahead.)
CREATE TABLE "partitions"."audit_logs_default"    PARTITION OF "audit_logs" DEFAULT;
CREATE TABLE "partitions"."notifications_default" PARTITION OF "notifications" DEFAULT;
CREATE TABLE "partitions"."ad_events_default"     PARTITION OF "ad_events" DEFAULT;

SELECT "ensure_monthly_partitions"(12, 3);
