#!/usr/bin/env bash
# Kafka's users and what each may do (D-092), from access.conf.
#
# Runs in the broker's own network namespace (network_mode: service:kafka) and talks to the
# broker's local listener: the only way in without a password, bound to 127.0.0.1 inside the
# broker's container, so nothing else can use it. Every other way in signs in (SCRAM-SHA-512).
#
# Users: buku-admin (topic set-up, tests from this machine: may do anything), buku-tools (the
# Kafka UI: may look, not change), and buku-<service> for each service in the plan. Each run
# makes Kafka match the plan exactly: passwords set, missing permissions added, and any other
# permission these users hold removed. Every Kafka tool is a JVM start (a second or two), so a
# run that finds the same plan and passwords as last time, and every user in place, stops there.
set -euo pipefail
# No filename expansion: "*" is a resource name here (every topic), never a file pattern.
set -f

BOOTSTRAP=127.0.0.1:29093
BIN=/opt/kafka/bin
PLAN=/access/access.conf
STATE=/home/appuser/applied
DLQ=dlq.failed-events

die() {
  echo "kafka-access: $*" >&2
  exit 1
}
tool() { "$BIN/$1" --bootstrap-server "$BOOTSTRAP" "${@:2}"; }

# ── The plan ──
declare -A PUBLISHES=() CONSUMES=()
SERVICES=()
while read -r service what topics; do
  [[ -z "$service" ]] && continue
  [[ "$service" =~ ^[a-z]+$ ]] || die "bad service name: $service"
  for t in $topics; do [[ "$t" =~ ^[a-z0-9._-]+$ ]] || die "$service: bad topic name: $t"; done
  case "$what" in
    publishes) PUBLISHES[$service]="${PUBLISHES[$service]:-} $topics" ;;
    consumes) CONSUMES[$service]="${CONSUMES[$service]:-} $topics" ;;
    *) die "$service: '$what' (expected publishes or consumes)" ;;
  esac
  [[ " ${SERVICES[*]} " == *" $service "* ]] || SERVICES+=("$service")
done < <(sed 's/#.*//' "$PLAN")
USERS=(admin tools "${SERVICES[@]}")

password_of() {
  local var="KAFKA_PASSWORD_${1^^}"
  local value="${!var:-}"
  # Generated by setup (hex); never anything that could break the SCRAM config string.
  [[ "$value" =~ ^[A-Za-z0-9]{32,}$ ]] || die "$var missing or not 32+ letters and digits (run pnpm bootstrap)"
  printf '%s' "$value"
}

# What the plan allows, one per line: principal operation resource-type pattern-type name.
expected() {
  local s t
  echo "User:buku-tools READ TOPIC LITERAL *"
  echo "User:buku-tools DESCRIBE_CONFIGS TOPIC LITERAL *"
  echo "User:buku-tools DESCRIBE GROUP LITERAL *"
  echo "User:buku-tools DESCRIBE CLUSTER LITERAL kafka-cluster"
  echo "User:buku-tools DESCRIBE_CONFIGS CLUSTER LITERAL kafka-cluster"
  for s in "${SERVICES[@]}"; do
    for t in ${PUBLISHES[$s]:-}; do echo "User:buku-$s WRITE TOPIC LITERAL $t"; done
    if [[ -n "${CONSUMES[$s]:-}" ]]; then
      for t in ${CONSUMES[$s]}; do echo "User:buku-$s READ TOPIC LITERAL $t"; done
      echo "User:buku-$s WRITE TOPIC LITERAL $DLQ"
      echo "User:buku-$s READ GROUP PREFIXED buku-$s-service-"
    fi
  done
}

# What Kafka holds now for our users, in the same form.
current() {
  tool kafka-acls.sh --list | awk '
    /ResourcePattern\(/ {
      match($0, /resourceType=[A-Z_]+/); type = substr($0, RSTART + 13, RLENGTH - 13)
      match($0, /name=[^,]+/); name = substr($0, RSTART + 5, RLENGTH - 5)
      match($0, /patternType=[A-Z]+/); pattern = substr($0, RSTART + 12, RLENGTH - 12)
    }
    /principal=User:buku-/ {
      match($0, /principal=[^,]+/); who = substr($0, RSTART + 10, RLENGTH - 10)
      match($0, /operation=[A-Z_]+/); op = substr($0, RSTART + 10, RLENGTH - 10)
      if ($0 ~ /permissionType=ALLOW/) print who, op, type, pattern, name
      else print who, "DENY:" op, type, pattern, name
    }'
}

# "DESCRIBE_CONFIGS" → "DescribeConfigs", as the tool takes it.
operation_arg() { awk -F_ '{ for (i = 1; i <= NF; i++) printf "%s%s", substr($i, 1, 1), tolower(substr($i, 2)); print "" }' <<<"$1"; }

resource_args() {
  case "$1" in
    TOPIC) echo "--topic $2" ;;
    GROUP) echo "--group $2" ;;
    CLUSTER) echo "--cluster" ;;
    *) die "unexpected resource type $1" ;;
  esac
}

passwords_hash=$(for u in "${USERS[@]}"; do printf '%s %s\n' "$u" "$(password_of "$u")"; done | sha256sum | cut -d' ' -f1)
plan_hash=$(cat "$PLAN" "$0" | sha256sum | cut -d' ' -f1)
fingerprint="$passwords_hash $plan_hash"

users_listed=$(tool kafka-configs.sh --describe --entity-type users)
all_users_present=true
for u in "${USERS[@]}"; do
  grep -q "user-principal 'buku-$u' are SCRAM-SHA-512" <<<"$users_listed" || all_users_present=false
done
if $all_users_present && [[ -f "$STATE" && "$(cat "$STATE")" == "$fingerprint" ]]; then
  echo "kafka-access: ${#USERS[@]} users and their permissions already in place"
  exit 0
fi

# ── Passwords ──
for u in "${USERS[@]}"; do
  tool kafka-configs.sh --alter --entity-type users --entity-name "buku-$u" \
    --add-config "SCRAM-SHA-512=[iterations=8192,password=$(password_of "$u")]" >/dev/null
done

# ── Permissions: add what's missing, remove what the plan doesn't list ──
want=$(expected | sort -u)
have=$(current | sort -u)
missing=$(comm -23 <(echo "$want") <(echo "$have") | sed '/^$/d')
extra=$(comm -13 <(echo "$want") <(echo "$have") | sed '/^$/d')

# One call per principal, operation and resource kind (each a JVM start).
while read -r key; do
  [[ -z "$key" ]] && continue
  read -r who op type pattern <<<"$key"
  args=()
  while read -r name; do
    # shellcheck disable=SC2207
    args+=($(resource_args "$type" "$name"))
  done < <(awk -v k="$key" '($1 " " $2 " " $3 " " $4) == k { print $5 }' <<<"$missing")
  tool kafka-acls.sh --add --allow-principal "$who" --operation "$(operation_arg "$op")" \
    --resource-pattern-type "${pattern,,}" "${args[@]}" >/dev/null
done < <(awk '{ print $1, $2, $3, $4 }' <<<"$missing" | sort -u)

while read -r who op type pattern name; do
  [[ -z "$who" ]] && continue
  if [[ "$op" == DENY:* ]]; then flag=--deny-principal op=${op#DENY:}; else flag=--allow-principal; fi
  # shellcheck disable=SC2046
  tool kafka-acls.sh --remove --force "$flag" "$who" --operation "$(operation_arg "$op")" \
    --resource-pattern-type "${pattern,,}" $(resource_args "$type" "$name") >/dev/null
  echo "kafka-access: removed $who $op on $type $name (not in the plan)"
done <<<"$extra"

echo "$fingerprint" >"$STATE"
echo "kafka-access: ${#USERS[@]} users ($(IFS=,; echo "${USERS[*]}")); $(echo "$want" | wc -l) permissions"
